# config
logo: /images/me.jpg
keywords: "ugurozalp, ugur ozalp, java developer"
menu:
  Home: /
  Articles: /articles
  About: /about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics: UA-102666875-1


links:
- url: 'https://twitter.com/Ugur_Ozalp'
  name: 'twitter'
- url: 'https://gitlab.com/ugurozalp'
  name: 'gitlab'
- url: 'https://github.com/ugurozalp'
  name: 'github'
- url: 'https://www.linkedin.com/in/ozalpugur'
  name: 'linkedin'
- url: 'https://www.instagram.com/ugur.ozalp_'
  name: 'instagram'
- url: 'mailto:blog@ugurozalp.com'
  name: 'envelope-o'
  self: true
